### ISSUE TITLE
Geneiase is not executed by job scheduler (Slurm)

### ISSUE THREAD

**Issue by sergiopalmavera** [edsgard/geneiase#1]
Geneiase has been properly installed, and I tested it with the provided test files.

I need to run it on 100 samples. When I try running it directly on the command line, geneiase starts without problems. But then I have to stop it, since I am working on a cluster and I should submit my jobs using an scheduler. We use slurm.

The problem is that when I submit a job, slurm does not return any error or standard output, even though the call worked in the command line.

**Comment by sergiopalmavera** [comment]
I figured out there was a typo in `#SBATCH --workdir=` which is why the job was immediately shot down without output. The job runs after fixing said typo

**Comment by edsgard** [comment]
Excellent that you could solve your slurm problem!
